<? 
include "../header1.inc.php";
$title="Schule als Tradition";
include "../header2.inc.php"; 
?>
<!--Content-->
<div id="center">
        <div id="content">
	  <a class="content" href="../index.php">Index &raquo;</a> <a class="content" href="index.php">Institut &raquo;</a> <a class="content" href="#">Schule als Tradition</a>
	  <div id="tabs-wrapper-lower"></div>
          <h3>Tradition?</h3>

          <p>Die Wortwurzel der <i>Tradition</i> ist das Weitergeben: Nicht stur an Bestehendem festzuhalten gilt es, sondern Wertvolles mit neuem Leben zu erf&uuml;llen und Verlorenes wiederzugewinnen, was aber nicht ausschlie&szlig;t, auch bislang unbetretene Pfade mutig zu begehen und ungeahnte Wege zu weisen. Die Erkenntnissuche ist eine alte Tradition, die Erkenntnisliebende &uuml;ber Generationen und &uuml;ber den Erdkreis miteinander verbindet. Auf diese Weise gelingt oft das Unm&ouml;gliche: &uuml;ber den Tod hinaus zu lehren und Menschen anzusprechen.</p>

          <a name="praktische_philosophie"></a>
          <p>Wir h&auml;ngen der traditionellen Perspektive an, die &Ouml;konomie - neben Ethik und Politik - als Teil der praktischen Philosophie anzusehen. Freilich haben auch diese Begriffe eine ganz andere Bedeutung als die, unter der man sie uns heute verkaufen will. Wir wollen das reale Handeln realer Menschen gr&uuml;ndlich verstehen, ohne ideologische und moralische Scheuklappen. Und wir halten es, in aller Bescheidenheit und ohne Anma&szlig;ung, f&uuml;r unsere Verantwortung, Orientierung zu bieten. Nichts halten wir von einer Ethik, die schnelle Rezepte und politische Allmachtsphantasien formuliert. Ethik ist f&uuml;r uns das Nachdenken &uuml;ber gute Gewohnheiten und gute Praxis im Sinne menschlicher Lebens&uuml;bung im Hier und Heute - ganz nach der urspr&uuml;nglichen griechischen Bedeutung: Die Kunst, in unserer Welt eine gute Heimst&auml;tte zu finden, uns diese Welt vertraut zu machen und in ihr ein gutes Leben zu f&uuml;hren. Politik meint dem klassischen und auch unserem Verst&auml;ndnis nach die Kunst, das Miteinander mit anderen Menschen gut zu gestalten und so eine Ordnung zu finden, die es in der Folge zu f&ouml;rdern und zu bewahren gilt und die uns dann erlaubt, unser menschliches Potential voll zu entfalten. Mit Parteipolitik, Fanatismus und dem Pragmatismus der Macht wollen wir nichts zu tun haben. &Ouml;konomik schlie&szlig;lich ist die Kunst, mit den uns anvertrauten Mitteln gut umzugehen, Werte zu schaffen wie zu erhalten und mit anderen eine Verbindung einzugehen, die beide Seiten ihren Zielen n&auml;her bringt. Oft sprechen wir auch von der &Ouml;konomie im Sinne des Nachdenkens &uuml;ber die Ph&auml;nomene der &Ouml;konomik. Der unrealistischen "Volkwirtschaftslehre" moderner "Experten" mit ihren absurden Modellen und Formalismen setzen wir das Nachdenken &uuml;ber das Handeln realer Menschen entgegen. Wir geh&ouml;ren zu den weltweit profundesten Kennern der Tradition der Wiener Schule der &Ouml;konomie, die vor allen anderen den homo oeconomicus als Zerrbild ablehnte und sich an realistischer &Ouml;konomie versuchte. Unsere eigene Tradition reicht jedoch weit &uuml;ber diese Schule hinaus. Wir h&auml;ngen keiner einzelnen "Schule" mit ideologischer Verbissenheit an. Eine "Schule" in dieser engeren Bedeutung ist ein Forschungsprogramm, bei dem man eine Weile lang auf dem selben Weg entlangl&auml;uft. Wir rechnen uns der alle Schulen transzendierenden und Jahrtausende alten Tradition des Nachdenkens &uuml;ber die Welt und den Menschen zu - der Tradition der Gelehrten.</p>

          <h5>Gelehrte?</h5>
          <p>Das Wort klingt heute allzu gro&szlig;, vielleicht, weil es nicht mehr in die Zeit zu passen scheint. Tats&auml;chlich war das traditionelle Selbstverst&auml;ndnis von Gelehrten stets als "Zwerge auf den Schultern von Riesen" zu stehen. Bescheidenheit ist deshalb die erste Tugend des Gelehrten, denn je gr&ouml;&szlig;er der Durchmesser unseres Wissens ist, desto gr&ouml;&szlig;er ist auch der Umfang unseres Nichtwissens. Schon die fr&uuml;hesten Philosophen haben dies erkannt. Neben der Vermittlung von Wissen ist die noch wichtigere Aufgabe des Gelehrten, Respekt vor unserem Nichtwissen zu vermitteln und der Hybris der vielen Besserwisser, die nach Macht dr&auml;ngen, einen D&auml;mpfer zu geben.</p>
          <p>Wir verwenden den Begriff des Gelehrten, weil er f&uuml;r uns einen klaren Gegensatz zum modernen Experten ausdr&uuml;ckt. Der Experte wei&szlig; immer mehr &uuml;ber immer weniger, bis er schlie&szlig;lich alles &uuml;ber nichts wei&szlig;. Heutige Universit&auml;ten bringen meist nur noch hochspezialisierte Disziplinen hervor, die sich untereinander kaum mehr verstehen, die nicht mehr zu den Menschen au&szlig;erhalb ihres engen Geheimbundes mit dessen Geheimsprache sprechen k&ouml;nnen, und die Realit&auml;t so weit zerst&uuml;ckeln, bis vollkommen unrealistische Hirnakrobatik dabei herauskommt. Die Universit&auml;t und der Universalgelehrte sind urspr&uuml;nglich von einem ganz anderen Zugang getragen. Die universitas ist die Gesamtheit und Gemeinsamkeit, in der die Welt nur verstanden werden kann. Wir sprechen der Spezialisierung nicht ihre Berechtigung ab. Wir behaupten blo&szlig;, da&szlig; es ein gro&szlig;er Verlust war, den unabh&auml;ngigen Universalgelehrten daf&uuml;r g&auml;nzlich aufzugeben. </p>
          <p>Einst hatten uns alle f&uuml;r verr&uuml;ckt gehalten, nicht geradlinig einer akademischen Karriere zu folgen und einen gutbezahlen Job als Experte im Dienst von Staat, Konzernen oder Banken anzustreben. Mit viel Einsatz und Leidenschaft haben wir es aber trotzdem geschafft, unseren eigenen Ort der Mu&szlig;e zu erobern, abseits einer gehetzter "Karriere" - und da&szlig; dieses Wort von "laufen" kommt, spricht B&auml;nde. Viele gibt es nicht, die den Mut haben, den Weg des unabh&auml;ngigen Gelehrten zu gehen. Darum war es nur nat&uuml;rlich, da&szlig; wir uns fanden. Unsere Schule verstehen wir als unsere Zunft, die uns selbst und Leuten, die diesen Weg ebenso gehen wollen, den R&uuml;cken st&auml;rkt.</p>

          <h5>Unser Logo</h5>
          <p><img class="semimg" src="../style/gfx/logo_s.png" alt="" >Das Symbol, das Sie neben unserem Schriftzug finden, steht sinnbildlich f&uuml;r unseren Zugang. Es handelt sich um eine alte Ligatur, die wir noch auf heutigen Tastaturen als "kaufm&auml;nnisches Und" finden: &. Erst im Betrachten der &auml;lteren Formen dieser Ligatur f&auml;llt auf, was sie eigentlich bedeutet. <i>Ligare</i> ist Latein f&uuml;r <i>verbinden</i>. Urspr&uuml;nglich sind hier ein "e" und ein "t" kunstvoll verbunden und ergeben <i>et</i> - das lateinische Wort f&uuml;r <i>und</i>. Bei diesem Wort handelt es sich um den sprachlichen Inbegriff der Verbindung. Ligaturen verweisen auf die abendl&auml;ndische Tradition des schriftbasierten Gelehrtentums. Die Ligatur ersparte dem Schreiberling in der Zeit vor Buchdruck und Digitalisierung das Absetzen der Feder, ohne die Sch&ouml;nheit des Schriftbilds falscher Effizienz zu opfern. </p>
          <p>Wir haben ein kaufm&auml;nnisches Symbol gew&auml;hlt, weil die Menschen heute oft erst zuh&ouml;ren, wenn es um ihr Geld geht. Doch um die &Ouml;konomie zu verstehen, an der sich oberfl&auml;chlich tieferliegende Dynamiken offenbaren, mu&szlig; man ein wenig in der Geschichte zur&uuml;ckgehen und in die Philosophie wagen. So ist es auch bei dieser Ligatur; und sie steht zugleich f&uuml;r jene gute &Ouml;konomik, die manche Denker Katallaktik nannten: <i>Katallein</i> bedeutet nicht nur tauschen, sondern auch "vom Feind zum Freund machen". Das ist die Essenz guter &Ouml;konomik: Menschen zu verbinden.</p>
          <p>Schlie&szlig;lich ist das Verbinden auch die Kernaufgabe des guten Gelehrten: Die Gr&auml;ben der Ideologien durch Erkenntnis und Austausch zu &uuml;berwinden und den alten Faden der Erkenntnis wiederaufzunehmen und neu zu verkn&uuml;pfen, wo er gerissen oder noch lose ist. In der gro&szlig;en Ligatur des Wissensliebe, die die Menschen eint, wo sie ihr Handeln trennt, wollen wir die Feder niemals absetzen.</p>

          <p><small>Wertewirtschaft&trade; und das Wertewirtschaft-Logo sind gesch&uuml;tzte Wort- bzw. Bildmarken. Alle Rechte vorbehalten.</small></p>

          <p><a href="zunft.php">&rarr;Lernen Sie die unabh&auml;ngigen Denker kennen, die im Institut Mu&szlig;e finden, eine Tradition am Leben halten und ihre Werke vorstellen.</a></p>
          <div id="tabs-wrapper-lower"></div>
        </div>
         <? include "../sidebar.inc.php"; ?>
        </div>
<? include "../footer.inc.php"; ?>