<?
$id=$HTTP_GET_VARS['id'];
$t=$HTTP_GET_VARS['t'];
$q=$HTTP_GET_VARS['q'];
$active="portrait";
include "/home/content/56/6152056/html/rahim/header1.inc.php";

include "/home/content/56/6152056/html/rahim/header2.inc.php";
?>
<td valign="top" width="600">
<div style="padding-left:10px">
<img src="stehend.jpg" alt="" border="0" align="right">
<h1>&Uuml;ber Rahim Taghizadegan</h1><p>Herzlich willkommen und besten Dank f&uuml;r Ihr Interesse an meinem Wirken. Ich bin ein junger austroiranischer Wirtschaftsphilosoph und lebe in Wien. Dort gr&uuml;ndete ich das <a href="http://wertewirtschaft.org">Institut f&uuml;r Wertewirtschaft</a>, eines der wenigen vollkommen unabh&auml;ngigen akademischen Institute in &Ouml;sterreich. Gemeinsam mit meinen Kollegen versuche ich die Krise der Gegenwart besser zu verstehen und Wege aufzuzeigen, wie heute wertvolles Wirtschaften und ein sinnvolles Leben aussehen k&ouml;nnte.</p>
<p>Mein ewiger Drang, wirklich zu verstehen, was die Welt im Innersten zusammenh&auml;lt, f&uuml;hrte mich quer durch die Wissenschaften. Ich begann meine Karriere in der Weltraumforschung, arbeitete f&uuml;r das Astronomische Institut, das U.S. Naval Observatory und das European Space Operations Center. Das Studium der Technischen Physik schlo&szlig; ich mit einer Spezialisierung in Atomphysik am letzten, da &ouml;ffentlich weitgehend unbekannten Forschungsreaktor &Ouml;sterreichs ab, widmete mich dem Studium komplexer Systeme und lernte an der &Eacute;cole Polytechnique F&eacute;d&eacute;rale de Lausanne eine sehr bodenst&auml;ndige, realistische Interpretation der Quantenphysik kennen, die mir manch Epiphanie er&ouml;ffnete. </p><p> Wirklich faszinierte mich hingegen stets das komplexeste aller Probleme, vor dem Physik und Mathematik klein beigeben m&uuml;ssen: Der Mensch und sein Handeln. Zur Verfolgung dieses Interesses studierte ich nebenbei Soziologie und Handelswissenschaft und sammelte Erfahrungen in Journalismus und Politik. F&uuml;r letztere war ich freilich denkbar ungeeignet, denn unter "Politik" verstand ich stets das Bem&uuml;hen, das menschliche Zusammenleben besser zu verstehen und zu gestalten, Parteipolitik ist mir vollkommen fern. </p><p>Bei l&auml;ngeren Aufenthalten in den USA lernte ich Wissenschaftler kennen, die sich einer Schule zurechneten, die einst aus &Ouml;sterreich fliehen mu&szlig;te und hierzulande nun nahezu unbekannt ist: Die Wiener Schule der &Ouml;konomie. Ich besuchte Seminare u.a. von Israel M. Kirzner, dem amerikanischen Sch&uuml;ler des &ouml;sterreichischen &Ouml;konomen Ludwig von Mises, und dem Nobelpreistr&auml;ger Vernon L. Smith. Mises' Hauptwerk, das auf Englisch unter dem sch&ouml;nen Titel "Human Action" erschien, er&ouml;ffnete einen Zugang zur &Ouml;konomie, der mir wesentlich realistischer schien als das geistlose Kopieren der Naturwissenschaften, das heute so in Mode ist. Mit meiner fundierten naturwissenschaftlichen Ausbildung war ich hier stets viel strenger und brachte bei meinem Studium zahlreiche &Ouml;konomieprofessoren mit meinen Einw&auml;nden zur Verzweiflung. Gew&ouml;hnliche &Ouml;konomiestudenten lassen sich nur allzu leicht von Formalismen beeindrucken.</p>
<p>Langsam erh&auml;rtete sich der Verdacht, da&szlig; in den Sozialwissenschaften, insbesondere der &Ouml;konomie, so wie sie heute gelehrt werden, vieles nicht mit rechten Dingen zugeht. Nach und nach stellte ich fest, wie eng das heutige Spektrum des Diskurses ist und wie viel Wissen im Wahnsinn des letzten Jahrhunderts verloren ging - insbesondere in &Ouml;sterreich.</p>
<p>Ich widmete mich also selbst dem Studium der &Ouml;konomie - im Sinne Mises': als Wissenschaft vom Handeln realer Menschen, nicht als Pseudowissenschaft, die mit k&uuml;nstlichen Modellen vorlieb nimmt. Dieser Zugang zur &Ouml;konomie ist viel intuitiver und ich gewann Freude daran, dieses Wissen anderen Menschen zu vermitteln. Einige Zeit f&uuml;hrte ich in S&uuml;dafrika &Ouml;konomieschulungen in Armenvierteln durch - fest davon &uuml;berzeugt, da&szlig; gute &Ouml;konomie jedem Menschen zug&auml;nglich sein m&uuml;&szlig;te. Die extrem positive Resonanz vor Ort best&auml;tigte dies.  </p>
<p>Schlie&szlig;lich lernte ich vor vielen Jahren den &Ouml;konomen Gregor Hochreiter bei einer Diskussionsreihe kennen, die ich damals veranstaltete (und noch heute in einem &auml;hnlichen Format fortf&uuml;hre). Beide lockten uns hoch bezahlte Jobangebote und eine klassische Universit&auml;tskarriere, doch wir teilten dasselbe Unbehagen &uuml;ber den "Mainstream". Mit jugendlichem Idealismus entschlossen wir uns so wider jede praktische Vernunft, unseren Weg vollkommen unabh&auml;ngig weiterzugehen. Unsere Devise: Wer, wenn nicht wir? Einige Jahre mu&szlig;ten wir freilich noch unseren Platz suchen und erk&auml;mpfen, das magere Einkommen fra&szlig; die Finanz g&auml;nzlich auf. Endlich fa&szlig;ten wir den Mut, eine Nische vollkommen unabh&auml;ngiger und kompromi&szlig;loser Erkenntnissuche und Wissensvermittlung zu gr&uuml;nden: Das Institut f&uuml;r Wertewirtschaft. </p>
<p>Im Zuge meiner Arbeit f&uuml;r das Institut f&uuml;r Wertewirtschaft verabschiedete ich mich von den Resten ideologischer Verk&uuml;rzungen, gewann einen kritischen Blick auch auf die Wiener Schule und widmete mich der Erkundung tats&auml;chlich realistischer &Ouml;konomie. Mein Weg f&uuml;hrte mich nun weit &uuml;ber die &Ouml;konomie hinaus, ich befasse mich viel mit Philosophie, Theologie und Geschichte, sowie praktischen Aspekten des guten Lebens in einem Zeitalter der Illusionen. Einen schlechten &Ouml;konomen erkennt man schlie&szlig;lich daran, da&szlig; er blo&szlig; &Ouml;konom ist. </p>
<p> Als interdisziplin&auml;rer Querdenker versuche ich mich nun insbesondere an der Aufdeckung moderner Illusionen, der Freilegung verlorenen Wissens und der Verkn&uuml;pfung der zahllosen aufgetrennten F&auml;den heutigen Denkens. Je tiefer ich in die Fragen der Zeit eindringe, desto deutlicher wird: Fast alles, was Menschen heute zu wissen glauben, ist falsch. Nach dem letzten Jahrhundert der Ideologien regieren eifers&uuml;chtige Bruchst&uuml;cke des Halbwissens, unhinterfragte Vorurteile, voreiliges Schubladisieren und realit&auml;tsfremde Utopien unser Denken. Ich hoffe, meinen bescheidenen Beitrag dazu leisten zu k&ouml;nnen, meinen Mitmenschen zu helfen, die heutige Welt besser zu verstehen, insbesondere die Krise der Gegenwart, und ein besseres Leben zu f&uuml;hren. </p>
<p>Zu diesem Zweck schreibe ich: meine Scholien - Randnotizen zur Zeit - , Artikel und B&uuml;cher; lehre ich - und Universit&auml;ten und dem Institut f&uuml;r Wertewirtschaft; halte ich Vortr&auml;ge im gesamten deutschsprachigen Raum (und gelegentlich dar&uuml;ber hinaus); leite ich Seminare, darunter eine j&auml;hrliche Sommerakademie im Kloster Pernegg, und lade einmal im Monat zum Salon ins Institut f&uuml;r Wertewirtschaft ein. Da&szlig; ich auf dem richtigen Weg bin, vermeine ich schon allein daran zu erkennen, da&szlig; ich dabei die wunderbarsten und interessantesten Menschen kennenlerne, Menschen, von denen man in Momenten der Ern&uuml;chterung gar nicht mehr glauben mag, da&szlig; es sie in Europa &uuml;berhaupt noch gibt. Diese "Remnants" - wie sie der US-Journalist Albert Jay Nock nannte - spreche ich an, Menschen, in deren Denken und Charakter die letzten &Uuml;berbleibsel erhalten sind, die wie durch ein Wunder das 20. Jahrhundert &uuml;berlebt haben. Wer sich nicht angesprochen f&uuml;hlt, dem will ich nichts dreinreden, das Missionieren liegt mir nicht. Wer aber die leise Ahnung versp&uuml;rt, da&szlig; wir auf der Suche nach &Auml;hnlichem sein k&ouml;nnten, den lade ich sehr herzlich ein, mich ein St&uuml;ck meines Weges zu begleiten.</p>
</td>
<?
include "/home/content/56/6152056/html/rahim/footer.inc.php";
?>
